### ISSUE TITLE
Dedupe dependencies

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/pundle#187]
Currently dependencies are loaded twice if they are found in different places.
We have two ways of solving this

- Either hash the file based on contents so regardless of where it is, we have only one version of it ever
- read the manifest files of the loaded modules and use the latest semver-compatible one

The first way won't let us do the latest version between semver-compatible versions so I am leaning towards the second way of fixing this

**Comment by natew** [comment]
Second seems better because minor differences in some sub-file in a 1.2.1 vs 1.2.0 package would not contain the patch if you wanted to force 1.2.1.

Not to bug but whats your rough estimate for this? I'm thinking if pundle works well enough it could power the in-app app development piece of Orbit to give it an extra wow factor.

**Comment by steelbrain** [comment]
Consider this about 40% done in this branch https://github.com/steelbrain/pundle/tree/deupe-plugin
