### ISSUE TITLE
Issues with babel-pundle.

### ISSUE THREAD

**Issue by AriaFallah** [steelbrain/pundle#62]
1. From my understanding of conventions created by Webpack, loaders are `String -> String` transformations of the contents of a file, and plugins modify the behavior of the bundler itself. For example, `CSS -> JS` (style-loader) is a loader, and `CommonChunksPlugin`, which does static analysis of your project as a whole is a plugin.

Given this definition, since babel does `ES6/7 -> ES5`, which boils down to `String -> String`, shouldn't it be classified as a loader?

---

2. What's the convention for naming pundle packages in the future going to be?

Currently you have `pundle`, `babel-pundle`, and `pundle-dev`, and then for the loaders (which don't exist?) you have `pundle-less` and `pundle-css`.

It seems like `babel-pundle` is the odd one out. Are you going to change the name to `pundle-babel` to reflect that?

What do you think of adopting a `pundle-plugin-*` and `pundle-loader-*` approach?

**Comment by AriaFallah** [comment]
Also as an addendum to this, what's the convention for naming pundle packages in the future going to be?

Currently you have `pundle, babel-pundle, and pundle-dev`, and then for the loaders (which don't exist?) you have `pundle-less` and `pundle-css`.

It seems like `babel-pundle` is the odd one out.

**Comment by steelbrain** [comment]
We could rename `babel-pundle` to `pundle-plugin-babel`. The main difference between a plugin and a loader is that the plugin just transforms the text, the loader is responsible for renaming all calls to require with `__require()` and asking pundle to resolve the require requests and wrapping the content of the module with vars like `__dirname` and `__filename`.

But because Babel is just a step in processing javascript modules and shouldn't need to define those variables mentioned above, it's just a plugin. Similar to how `postcss` would be a plugin and `css` would be a loader

**Comment by AriaFallah** [comment]
Ok so really a module bundler is analogous to an ETL framework for JavaScript.

extract = require
transform = plugins
load = loaders

Makes more sense than the Webpack approach tbh. However, it might be smart to make transformation separate from the concept of a plugin such that a plugin can have impure side-effects or change the behavior of pundle globally, but a transform is only a pure `String -> String` transform.
