### ISSUE TITLE
transforming sister modules

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#90]
Consider a project that includes many modules in a monorepo:

```
packages/module-1/devServer.js
packages/module-1/src/index.ts
packages/module-1/dist/index.js

packages/module-1/node_modules/my-project-module-2 points at:

packages/module-2/src/index.ts
packages/module-2/dist/index.js
```

Is there a way to ask pundle to watch/transform `module-2` from the `module-1` dev server?  It would have to

1. know that `node_modules` that start with `my-project` are fair-game for watching/transforming, and
2. know to look in `src` instead of `dist` for those dependencies

As I understand it now, I have to rebuild `module-2/dist` whenever I make changes to `module-2/src`, otherwise, pundle won't find the changes.

**Comment by steelbrain** [comment]
Hi @appsforartists 

To make pundle compile `src/` instead of `dist/` of a module you have to set it's `browser` field to the src directory. There is also [a spec](https://github.com/defunctzombie/package-browser-field-spec) for the browser field.

At the time of writing these are the ordered priorities when loading modules in pundle by default

<img src="https://cloud.githubusercontent.com/assets/4278113/20724682/08b84a00-b624-11e6-9f29-c9371cb80d28.png">

**Comment by appsforartists** [comment]
Thanks.  So:

1. Point esnext:main at `./src` in each package.json, and
2. configure pundle to not-ignore node_modules if they start with `my-package`?

**Comment by appsforartists** [comment]
Looks like this is controlled with hardcoded values in pundle v1:

```js
// pundle/lib/resolver.js#152
return remoteManifest.browser 
  ? Resolver.resolveRemoteBrowserField(request, remoteManifest) 
  : remoteManifest.main;
```

and via the config key [`packageMains` in pundle v2](https://github.com/motion/pundle/blob/steelbrain/v2/packages/resolver-default/src/index.js#L135).

**Comment by appsforartists** [comment]
Not working as expected.  See http://codereview.cc/D2470

**Comment by steelbrain** [comment]
Thank you for letting me know, gonna try to repro and will post my findings

**Comment by appsforartists** [comment]
Thanks for your help.  Fixed in http://codereview.cc/D2470
